### ISSUE TITLE
Update event bus docs

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#465] opened 2023-10-05 13:06 UTC
There has been considerable drift in the event bus docs.

A/C:

- [ ] Wiki docs have the latest directions and recommendations.
  - Public: https://openedx.atlassian.net/wiki/spaces/AC/pages/3508699151/How+to+start+using+the+Event+Bus
  - 2U internal: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/174555142/How+to+Use+the+Event+Bus+edX.org+2+of+2
    - For example, Arch-BOM no longer needs to create topics for other teams (they can use terraform)

**Comment by rgraber** [comment] 2023-10-05 14:15
Possible duplicate of https://github.com/openedx/openedx-events/issues/238

**Comment by timmc-edx** [comment] 2023-10-11 13:49
Becca may add more pointers to known-outdated info. Have decided this is not a duplicate of the openedx-events issue.

**Comment by rgraber** [comment] 2023-11-06 13:03
The main thing that is out of date is how to set up topics, keys, etc. using Confluent.

**Closed** 2024-01-26 16:42 UTC
Labels: event-bus
