### ISSUE TITLE
Run pull_translations in Devstack images

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#579] opened 2024-03-21 15:52 UTC
New devstack builds are getting a blank login page until the dev runs `make pull_translations` in lms-shell.

**Comment by mfarhan943** [comment] 2024-11-06 14:08
I pulled the latest image and tested it locally, and I didn’t encounter any issues with the login page.

**Comment by mfarhan943** [comment] 2024-11-07 07:59
@timmc-edx , could you please close this issue? We couldn't reproduce the problem locally.

**Closed** 2024-11-07 13:32 UTC
